### ISSUE TITLE
lds_all_models.h

### ISSUE THREAD

**Issue by tbalatka** [kaiaai/firmware#1]
Hello, Compiling fails using the Arduino IDE. Can't locate "lds_all_models.h".

**Comment by kaiaai** [comment]
Thanks for reporting. I've fixed it. Please install Arduino LDS library version 0.5.1 with the fix.
It may take around 24 hours for this new LDS library release to propagate/show up in the Arduino library manager.
If you need to use it right away with the older LDS library version 0.5.0, just rename `lds_all_models.h` to `LDS_all_models.h`.

**Comment by tbalatka** [comment]
Excellent! Thanks so much!
Thomas
